# Site settings
title: Raula Gaikovina Kula
description: Personal Website
baseurl: "" # the subpath of your site, e.g. /blog
url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Raula Gaikovina Kula
user_description: Assistant Professor @ NAIST, Japan
email: raula-k@naist.jp
twitter_username: lorem_ipsum
github_username:  lorem_ipsum
gplus_username:  lorem_ipsum
disqus_username: lorem_ipsum

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Research
    url: /tags
  - title: Blogs
    url: /about

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
